/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

//#include "default.h"
#include "rcc.h"
#include "t_delay.h"
#include "t_pwm.h"
#include "gpio.h"
#include "spi.h"
#include "uart.h"


#include "w25q128jv.h"
/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

#include "stm32f1xx.h"


char rx_buf[1025];
char tx_buf[10];

int main(void)
{

	 system_clk();
	 uart_init();
	 timer_initialise();
     pwm_init();


	 uart_tran_byte('b');
	 uart_tran_string("hsjkxns");
	 uart_tran_string("hsjkxns");

	 spi_init();

     char p,q,r;


     char * tran_buff = "0000/285444500/771888200/00100/255/000/010/0000/285444500/771888200/00100/255/000/010/0000/285444500/771888200/00100/255/000/010/\n";

	while(1)
	{

		delay_ms(100);

		 p = ReadSR(ReadSR1);
		 q = ReadSR(ReadSR2);
		 r = ReadSR(ReadSR3);

		 erase_sector4KB(read_addr1);
		 delay_ms(100);
		 W25_Write_Data(read_addr1,tran_buff,135);
		 delay_ms(100);
		 W25_Read_Data(read_addr1,rx_buf,135);
		 delay_ms(100);
		 uart_tran_string(rx_buf);
		 uart_tran_string("\n");

		    /*
	GPIOA->ODR &= ~GPIO_ODR_ODR4;
	spi_mast_tran_byte(x);
	spi_mast_recv_byte();
	spi_mast_recv_byte();
	spi_mast_recv_byte();
	spi_mast_recv_byte();
	GPIOA->ODR |= GPIO_ODR_ODR4;
*/
		delay_ms(100);
	}
}

