/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "gb_gpio.h"
#include "gb_rcc.h"
#include "GB_UART.h"
#include "gb_t_delay.h"
#include "stm32f1xx.h"
#include "gb_dht11.h"

//Debug Exception and Monitor Control Register base address
#define DEMCR        			*((volatile uint32_t*) 0xE000EDFCU )

/* ITM register addresses */
#define ITM_STIMULUS_PORT0   	*((volatile uint32_t*) 0xE0000000 )
#define ITM_TRACE_EN          	*((volatile uint32_t*) 0xE0000E00 )


int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		//__io_putchar(*ptr++);
		 ITM_SendChar(*ptr++);
	}
	return len;
}

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/


int main(void)
{

	system_clk();
	timer_initialise();
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;
	timer4_init();
	GB_uart_init1();
	GB_printString1("Bus Voltage: ");
	SystemCoreClockUpdate();
	Gpio_output_pushpull_conf();

	while(1)

	  {

//		TIM4->CNT=0; // initialise counter register
//		SET_BIT(GPIOC->ODR, GPIO_ODR_ODR13);
//		while(TIM4->CNT <=133);
//		TIM4->CNT=0; // initialise counter register
//		CLEAR_BIT(GPIOC->ODR, GPIO_ODR_ODR13);
//		TIM4->CNT=0; // initialise counter register
//		while(TIM4->CNT <=133);

		GB_dht11();
		GB_printString1("Temperature : ");
		GB_float_value1(GB_dht11_temp());
		GB_printString1("\n");
		delay_ms(1000);
	  }
}
