/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>
 *
 * &copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * </center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <gb_gpio.h>
#include <gb_rcc.h>
#include <GB_UART.h>
#include <gb_t_delay.h>
#include "GB_adc.h"

#include "stm32f1xx.h"
/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/


#define DEMCR        			*((volatile uint32_t*) 0xE000EDFCU )

/* ITM register addresses */
#define ITM_STIMULUS_PORT0   	*((volatile uint32_t*) 0xE0000000 )
#define ITM_TRACE_EN          	*((volatile uint32_t*) 0xE0000E00 )


int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		//__io_putchar(*ptr++);
		 ITM_SendChar(*ptr++);
	}
	return len;
}

uint16_t RxData[3];
uint32_t adc;
void DMA1_Channel1_IRQHandler(void)
{
		//transfer complete
		if((DMA1->ISR)&(DMA_ISR_TCIF1)) //DMA Full Transfer complete
			{
			DMA1->IFCR|=DMA_IFCR_CTCIF1; // Setting the CTCIF1 bit, Clears the TCIF1 Flag of DMA_ISR Register
		while((DMA1->ISR & DMA_ISR_TCIF1)); // Wait till TCIF1 flag is cleared
			}

	//HALF transfer complete
			if((DMA1->ISR)&(DMA_ISR_HTIF1)) //DMA Half Transfer complete
				{
				DMA1->IFCR|=DMA_IFCR_CHTIF1;  // Setting the CHTIF1 bit, Clears the HTIF Flag of DMA_ISR register
			while((DMA1->ISR & DMA_ISR_HTIF1)); // Wait till HTIF1 flag is cleared
				}
}

int main(void)
{
	system_clk();
	timer_initialise();
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;
	//Gpio_output_pushpull_conf();

	GB_uart_init1();
	GB_printString1("ADC Driver");
	//adc_init(); // For Initialising adc for 1 channel

	adc_init_multichannel();  // Fpr Initialising ADC for multiple channels by using DMA
	dma_init((uint32_t) &ADC1->DR, (uint32_t)RxData, 3); //SEE GB_ADC.C
	dma_adc_convert();  //SEE GB_ADC.C

while(1)
{

}
}
