/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "stm32f1xx.h"
//#include "default.h"
#include "rcc.h"
#include "t_delay.h"
#include "gpio.h"
#include "GB_millis_systick.h"
#include "GB_uart.h"
#include "GB_ESP8266_Basic.h"
#include "GB_esp8266_server.h"

#define gb_RX_BUFFER_SIZE_UART2 500


extern char gb_RX_DATA_UART2[gb_RX_BUFFER_SIZE_UART2];
/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/
int main(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
		AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;


		systick_millis(32000);
		system_clk();
		timer_initialise();
		//terminal
		GB_uart_init1();
		GB_printString1("\nSTM32 ESP8266 Device Driver\n");
		GB_printString1("\nKunal Gupta\n");
		//ESP8266
		GB_uart_init2();
		__NVIC_EnableIRQ(USART2_IRQn);
		__NVIC_SetPriority (USART2_IRQn, 1);

		int gb_c=0;
		char gb_staip[20],gb_stamac[20];
    /*
     * Loop forever
     *
     * */
		while(1)
		{

			if(gb_c<1)
               {
                   //Configure as Station
                   GB_send_command("AT+CWMODE=1\r\n");
                   GB_RFR_UART2("OK",1000);
                   //GB_getstring_UART2();
                   GB_printString1(gb_RX_DATA_UART2);


                   //Start Multiple connection
                   GB_send_command("AT+CIPMUX=1\r\n");
                   GB_RFR_UART2("OK",1000);
                   //GB_getstring_UART2();
                   GB_printString1(gb_RX_DATA_UART2);

                   GB_send_command("AT+CIPSERVER=1,80\r\n");
                   GB_RFR_UART2("OK",1000);
                   GB_printString1(gb_RX_DATA_UART2);

                   GB_send_command("AT+CWJAP?\r\n");
                   GB_RFR_UART2("OK",1000);
                   //GB_getstring_UART2();
                    GB_printString1(gb_RX_DATA_UART2);

	              //  Connect To wifi
               //     GB_send_command("AT+CWJAP=\"Kunal\",\"Pottypotty12\"\r\n");
                   GB_send_command("AT+CWJAP=\"JioFiber 2.4ghz\",\"Mansi5481\"\r\n");
                  //  GB_send_command("AT+CWJAP=\"LALIT\",\"POTTYPOTTY\"\r\n");
                    GB_RFR_UART2("OK",10000);
                    GB_printString1(gb_RX_DATA_UART2);

                    GB_send_command("AT+CIFSR\r\n");
                    GB_RFR_UART2("OK",1000);

                    //GB_printString1(gb_RX_DATA_UART2);


                      memset(gb_staip, '\0',sizeof(gb_staip));
                      memset(gb_stamac, '\0',sizeof(gb_stamac));
                      char * gb_p = strstr(gb_RX_DATA_UART2,"+CIFSR:STAIP");
                      gb_p += strlen("+CWJAP:STAIP")+2;
                      char * gb_q=strchr(gb_p,'"');
                       strncpy(gb_staip,gb_p,gb_q-gb_p);
                      GB_printString1("IP address of Station is :");
                      GB_printString1(gb_staip);

                       // GB_printString1("\n");
                       // GB_printString1(gb_p);
                       // char * gb_r = strstr(gb_RX_DATA_UART2,"+CIFSR:STAMAC");
                       // gb_r += strlen("+CIFSR:STAMAC")+2;
                       // char * gb_s =strchr(gb_r,'"');
                       // strncpy(gb_stamac,gb_r,gb_s-gb_r);
                       //printString1("\n Mac address of Station is :");
                       //printString1(stamac);

                        // GB_send_command("AT+CIPSTO?\r\n");
                         // GB_getstring_UART2();


                        gb_c++;

                         GB_printString1("\n***********Waiting For Client to connect********\n");
                         GB_printString1("Browse IP address on the local Web-Browser:");
                         GB_printString1(gb_staip);
                         GB_printString1("\n");
               }

			uint8_t gb_g=0;
			gb_g = GB_getstring_ESP8266FORSERVER(gb_staip);
			GB_printString1("gb_g =");
			GB_decimel1(gb_g);
			GB_printString1("\n");
				if(gb_g==1)
				{
					GB_esp8266_serverdatatoclientcipsend();
					delay_ms(200);
				GB_esp8266_webpagedata();
				delay_ms(200);
				GB_esp8266_webpageclose();
				delay_ms(200);
				}

				delay_ms(5000);


		}
}
