/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "stm32f1xx.h"
//#include "default.h"
#include "rcc.h"
#include "t_delay.h"
#include "gpio.h"
#include "GB_millis_systick.h"
#include "GB_uart.h"
#include "GB_ESP8266_Basic.h"

// UART Port 0 is connected between MCU(Atmega 2560) and Laptop for printing data on terminal screen
  // UART Port 1 is connected between MCU( ATmega 2560) and ESP8266 for sending and receiving data via AT commands

  //const char gb_urlpath[100] ="/data/2.5/weather?q=delhi&appid=885e9149105e8901c9809ac018ce8658";
  //const char gb_url[100] = "api.openweathermap.org";
 // const char gb_urlpath[100] ="/update?api_key=K86PTN9OPANWW8MF&field1";
 // const char gb_url[100] = "api.thingspeak.com";

int main(void)
{
	systick_millis(32000);
	system_clk();
	timer_initialise();
	//terminal
	GB_uart_init1();
	GB_printString1("\nSTM32 ESP8266 Device Driver\n");
	GB_printString1("\nKunal Gupta\n");
	//ESP8266
	GB_uart_init2();
	__NVIC_EnableIRQ(USART2_IRQn);
	__NVIC_SetPriority (USART2_IRQn, 1);
	GB_esp8266_initialise_client();
    /* Loop forever */
	while(1)
	{

	//uint8_t gb_t = 90;
	//GB_esp8266_connectTCPserver(gb_url,80);
	//GB_esp8266_cipsend(gb_t,gb_urlpath);
	//GB_esp8266_tcpgetcommand(gb_urlpath,gb_t);
	//delay_ms(2000);
	//gb_t++;

	}
}
