/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h> //
#include "rcc.h"
#include "t_delay.h"
#include "gpio.h"
#include "i2c.h"
#include "stm32f1xx.h"

#define DEMCR        			*((volatile uint32_t*) 0xE000EDFCU )

/* ITM register addresses */
#define ITM_STIMULUS_PORT0   	*((volatile uint32_t*) 0xE0000000 )
#define ITM_TRACE_EN          	*((volatile uint32_t*) 0xE0000E00 )


int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		//__io_putchar(*ptr++);
		 ITM_SendChar(*ptr++);
	}
	return len;
}


/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

#define RTC_WADDR 0b11010000   //Slave Write
#define RTC_RADDR 0b11010001   //Slave Read

#define Status_reg 0x0F
#define Control_reg 0x0E
#define Date_reg 0x03
#define Time_reg 0x00
#define Alarm1_reg 0x07
#define Alarm2_reg 0x0B
#define Temp_reg 0x11


struct alarm1
{
	uint8_t sec;
	uint8_t min;
	uint8_t hour;
	uint8_t wday;
	uint8_t day;
};

uint8_t msb;
	uint8_t lsb;

int main(void)
{
	system_clk();
	timer_initialise();

	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;
	Gpio_output_pushpull_conf();

	master_init();

    /* Loop forever */
	while(1)
	{

		printf("hello world \n");

		GPIOC->ODR &= ~GPIO_ODR_ODR13;


		// writing a byte
		i2c_start_condition_w();
		i2c_address_send_w(RTC_WADDR);
		databyte_send(Temp_reg);
		stop_generation();

		//reading a byte
		i2c_start_condition_r();
		i2c_address_send_r(RTC_RADDR);
		//msb = databyte_receive_nack();//1 byte
		databyte_receive_ack(msb,lsb);
		stop_generation();

		delay_ms(100);
		GPIOC->ODR |= GPIO_ODR_ODR13;

		delay_ms(100);


	}

}
