/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "rcc.h"
#include "t_delay.h"
#include "gpio.h"

#include "GB_uart.h"



#include "stm32f1xx.h"
char d;


#define NVIC_PRIORITYGROUP_4         0x00000003U /*!< 4 bits for pre-emption priority
                                                      0 bits for subpriority */


/*********functions for generating millis()*******/

volatile uint32_t GB_counter;  //variable for millis counter

//system_tick handler on reaching 0
void SysTick_Handler(void)
{
	//GB_printString1("Get\n");
    GB_counter++;    // equivalent to HAL_IncTick(void)
}


//equivalent to  HAL_GetTick(void)
uint32_t GB_millis()
{
	//GB_printString1("Kun\n");
  return GB_counter;
}

int main(void)
{

	//Configuring the systick peripheral of ARM CortexM for using it as time base source for millis()
	FLASH->ACR |= FLASH_ACR_PRFTBE|FLASH_ACR_LATENCY_1;
	NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);
	SysTick_Config(32000);
	NVIC_SetPriority(SysTick_IRQn,0);

     system_clk();
	 timer_initialise();


	 GB_uart_init1();


    /* Loop forever */
	while(1)
	{
		GB_decimel1(GB_millis());
		GB_printString1("\n");
		delay_ms(1000);
	}
}

/*
 * Interrupts funtion
 * 	GB_decimel1(__NVIC_GetEnableIRQ(SysTick_IRQn));
	GB_decimel1(__NVIC_GetEnableIRQ(USART1_IRQn));
	GB_decimel1(__NVIC_GetActive(USART1_IRQn));
	*/

