/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>
#include <gb_gpio.h>
#include <gb_rcc.h>
#include <GB_UART.h>
#include <gb_t_delay.h>
#include "GB_adc.h"

#include "stm32f1xx.h"
/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

#define DEMCR        			*((volatile uint32_t*) 0xE000EDFCU )

/* ITM register addresses */
#define ITM_STIMULUS_PORT0   	*((volatile uint32_t*) 0xE0000000 )
#define ITM_TRACE_EN          	*((volatile uint32_t*) 0xE0000E00 )


int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		//__io_putchar(*ptr++);
		 ITM_SendChar(*ptr++);
	}
	return len;
}
uint32_t adcValue = 0,adcSumVal = 0;
float Voltage,VRMS,AmpsRMS;
	float sensitivity = 0.1;  // for 20A module
	float rawVoltage;
	float current;
	float adcAvgValue;
int main(void)
{
	system_clk();
	timer_initialise();
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;
	//Gpio_output_pushpull_conf();

	GB_uart_init1();
	adc_init();
//	GB_printString1("ADC Driver");


	while(1)
	{

//		for(int i=0;i<10;i++)
//		{
		adcValue = adc_convertPOL_START();
//		adcSumVal += adcValue;
//		delay_ms(2);
//		}
//		adcAvgValue = adcSumVal/10;
		Voltage = ((adcValue * 3.3)/4095);
		//for DC
		current =(Voltage - 2.5)/sensitivity;
		delay_ms(1000);


		//for AC
//		VRMS = (Voltage/2)*0.707;
//		AmpsRMS = ((VRMS * 1000)/185);
//
//		GB_float_value1(Voltage);
//				delay_ms(1000);
//				GB_printString1("\n");

	}
}
