/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <gb_gpio.h>
#include <gb_i2c.h>
#include <gb_rcc.h>
#include <gb_t_delay.h>
#include <stdint.h>
#include <stdio.h>
#include "gb_lcd_i2c_pcf8574.h"
#include "stm32f1xx.h"
/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

#define DEMCR        			*((volatile uint32_t*) 0xE000EDFCU )

/* ITM register addresses */
#define ITM_STIMULUS_PORT0   	*((volatile uint32_t*) 0xE0000000 )
#define ITM_TRACE_EN          	*((volatile uint32_t*) 0xE0000E00 )


int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		//__io_putchar(*ptr++);
		 ITM_SendChar(*ptr++);
	}
	return len;
}
uint8_t gb_Heart[8] = {
0b00000,
0b01010,
0b11111,
0b11111,
0b01110,
0b00100,
0b00000,
0b00000
};

uint8_t gb_Bell[8] = {
0b00100,
0b01110,
0b01110,
0b01110,
0b11111,
0b00000,
0b00100,
0b00000
};


uint8_t gb_Alien[8] = {
0b11111,
0b10101,
0b11111,
0b11111,
0b01110,
0b01010,
0b11011,
0b00000
};

uint8_t gb_Check[8] = {
0b00000,
0b00001,
0b00011,
0b10110,
0b11100,
0b01000,
0b00000,
0b00000
};

uint8_t gb_Speaker[8] = {
0b00001,
0b00011,
0b01111,
0b01111,
0b01111,
0b00011,
0b00001,
0b00000
};


uint8_t gb_Sound[8] = {
0b00001,
0b00011,
0b00101,
0b01001,
0b01001,
0b01011,
0b11011,
0b11000
};


uint8_t gb_Skull[8] = {
0b00000,
0b01110,
0b10101,
0b11011,
0b01110,
0b01110,
0b00000,
0b00000
};

uint8_t gb_Lock[8] = {
0b01110,
0b10001,
0b10001,
0b11111,
0b11011,
0b11011,
0b11111,
0b00000
};
uint8_t youtube[8] = {

		0b00000,
		0b01000,
		0b01100,
		0b01010,
		0b01001,
		0b01010,
		0b01100,
		0b01000
};

uint8_t Gettobyte[8] = {

		0b00000,
		0b01110,
		0b01000,
		0b01000,
		0b01011,
		0b01001,
		0b01111,
		0b00000
};


int main(void)
{
	system_clk();
	timer_initialise();

	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;
	Gpio_output_pushpull_conf();
	GB_LCD_init();
	GB_lcd_clear();
	GB_LCD_string("G");
    /* Loop forever */
	while(1)
	{
		GB_lcd_setcursor(0,0);
		GB_LCD_string("Gettobyte");
		delay_ms(10);
		GB_LCD_sendpattern(0,Gettobyte);
		GB_lcd_setcursor(10, 0);
		GB_LCD_printpattern(0);
		GB_lcd_setcursor(0,1);
		GB_LCD_string("Youtube");
		delay_ms(10);
		GB_LCD_sendpattern(1,youtube);
		GB_lcd_setcursor(10, 1);
		GB_LCD_printpattern(1);


	}


}
