/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#include <stdint.h>
#include "gb_gpio.h"
#include "gb_rcc.h"
#include "GB_UART.h"
#include "gb_t_delay.h"
#include "GB_millis_systick.h"
#include "stm32f1xx.h"
#include "gb_timer_input_capture.h"
#include "hlw8012_baremetal.h"
#include "gb_ssd1306.h"
#include "GB_ESP8266_Basic.h"
#include "GB_ESP8266_client.h"

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

#define UPDATE_TIME                     2000

#define DEMCR        			*((volatile uint32_t*) 0xE000EDFCU )

/* ITM register addresses */
#define ITM_STIMULUS_PORT0   	*((volatile uint32_t*) 0xE0000000 )
#define ITM_TRACE_EN          	*((volatile uint32_t*) 0xE0000E00 )


int _write(int file, char *ptr, int len)
{
	int DataIdx;

	for (DataIdx = 0; DataIdx < len; DataIdx++)
	{
		//__io_putchar(*ptr++);
		 ITM_SendChar(*ptr++);
	}
	return len;
}

#define CURRENT_RESISTOR                0.001
#define VOLTAGE_RESISTOR_UPSTREAM       ( 5 * 470000 ) // Real: 2280k
#define VOLTAGE_RESISTOR_DOWNSTREAM     ( 1000 ) // Real 1.009k


const char gb_urlpathcurrent[100] ="/update?api_key=K86PTN9OPANWW8MF&field1";
const char gb_urlpathvoltage[100] ="/update?api_key=K86PTN9OPANWW8MF&field2";
const char gb_url[100] = "api.thingspeak.com";

//const char gb_urlpath[100] ="https://api.thingspeak.com/update?api_key=K86PTN9OPANWW8MF&field1=0&field2=6";
//const char gb_url[100] = "api.thingspeak.com";



int main(void)
{
	  RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
		AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;
	    systick_millis(32000);
	    system_clk();
		timer_initialise();

		ssd1306_init();
		ssd1306_clear(GB_SSD1306_COLOR_BLACK);
		ssd1306_update_data();


		GB_uart_init1();  //terminal
		GB_printString1("Timer input capture\n");
		GB_uart_init2();  	//ESP8266
			__NVIC_EnableIRQ(USART2_IRQn);
			__NVIC_SetPriority (USART2_IRQn, 1);
			GB_esp8266_initialise_client();

		gb_t4_input_capture();
		__NVIC_SetPriority (TIM4_IRQn, 0);
		__NVIC_EnableIRQ(TIM4_IRQn);

		hlw8012_config();
		hlw8012_setResistors(CURRENT_RESISTOR, VOLTAGE_RESISTOR_UPSTREAM, VOLTAGE_RESISTOR_DOWNSTREAM);
//		GB_printString1(" Default Current Multiplier");
//		GB_decimel1(hlw8012_getcurrent_multiplier());
//		GB_printString1(" Default Voltage Multiplier");
//		GB_decimel1(hlw8012_getvoltage_multiplier());
//		GB_printString1(" Default Power Multiplier");
//		GB_decimel1(hlw8012_getpower_multiplier());

		hlw8012_calibrate();

		while(1)
		{


			ssd1306_GotoXY(0, 0);
			ssd1306_print_string("Connecting to web server:", GB_SSD1306_COLOR_WHITE);
			ssd1306_update_data();
			GB_esp8266_connectTCPserver(gb_url,80);

			ssd1306_GotoXY(0, 15);
			ssd1306_print_string("Now sending data, server connected:", GB_SSD1306_COLOR_WHITE);
			ssd1306_update_data();
		   // GB_esp8266_cipsendfloat(hlw8012_getcurrent(),gb_urlpathcurrent);
			 GB_esp8266_cipsendfloat(hlw8012_getvoltage(),gb_urlpathvoltage);

		    ssd1306_GotoXY(0, 24);
		    ssd1306_print_string("DataSend and readings are:", GB_SSD1306_COLOR_WHITE);
		    ssd1306_update_data();
			//GB_esp8266_tcpgetcommandfloat(gb_urlpathcurrent,hlw8012_getcurrent());
		    GB_esp8266_tcpgetcommandfloat(gb_urlpathvoltage,hlw8012_getvoltage());
		    delay_ms(2000);


		    GB_esp8266_connectTCPserver(gb_url,80);
		    GB_esp8266_cipsendfloat(hlw8012_getcurrent(),gb_urlpathcurrent);
		    GB_esp8266_tcpgetcommandfloat(gb_urlpathvoltage,hlw8012_getvoltage());

			ssd1306_GotoXY(0, 40);
		    ssd1306_print_string("Current:", GB_SSD1306_COLOR_WHITE);
		    ssd1306_float(hlw8012_getcurrent(),GB_SSD1306_COLOR_WHITE);
		    ssd1306_print_string(" A", GB_SSD1306_COLOR_WHITE);
		    ssd1306_update_data();

			ssd1306_GotoXY(0, 48);
		    ssd1306_print_string("Voltage:", GB_SSD1306_COLOR_WHITE);
		    ssd1306_float(hlw8012_getvoltage(),GB_SSD1306_COLOR_WHITE);
		    ssd1306_print_string(" V", GB_SSD1306_COLOR_WHITE);
			ssd1306_update_data();


//			        GB_printString1("Current in AMPS: ");
//			        GB_float_value1(hlw8012_getcurrent());
//			        GB_printString1("A");
//			        GB_uart_newline1();
//
//			        GB_printString1("Voltage in Volts: ");
//			       	GB_float_value1(hlw8012_getvoltage());
//			       	GB_printString1("V");
//			       	GB_uart_newline1();
		}
}
