/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "stm32f1xx.h"
//#include "default.h"
#include "rcc.h"
#include "t_delay.h"
#include "gpio.h"
#include "GB_millis_systick.h"
#include "GB_uart.h"
#include "GB_ESP8266_Basic.h"

int main(void)
{
	systick_millis(32000);
	system_clk();
	timer_initialise();
	//terminal
	GB_uart_init1();
	GB_printString1("\nSTM32 ESP8266 device driver\n");
	GB_printString1("\nKunal Gupta\n");
	//ESP8266
	GB_uart_init2();
	__NVIC_EnableIRQ(USART2_IRQn);
	__NVIC_SetPriority (USART2_IRQn, 1);
	GB_esp8266_initialise_client();
    /* Loop forever */
	while(1)
	{

	}
}
